version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-marketflow
    restart: always
    environment:
      POSTGRES_USER: marketflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-marketflow
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  exchange1:
    image: exchange1:latest
    container_name: exchange1
    restart: always
    ports:
      - "40101:40101"

  exchange2:
    image: exchange2:latest
    container_name: exchange2
    restart: always
    ports:
      - "40102:40102"

  exchange3:
    image: exchange3:latest
    container_name: exchange3
    restart: always
    ports:
      - "40103:40103"

  marketflow:
    build: .
    container_name: marketflow
    depends_on:
      - postgres
      - redis
      - exchange1
      - exchange2
      - exchange3
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  pg_data:
  redis_data:
